# Site information
site_name: Writing Resources
site_author: Kyle Weishaar
site_description: A learning portal for working with git as a source control for Flare documentation
repo_url: https://github.com/kyleweishaar/git-site
# Uncomment the line below to specify a new local port if 8000 is busy.
# dev_addr: 127.0.0.1:<your-port-number>`

# Site theme
# You can download and install other themes. You'll need add the new theme here.
theme:
  name: material
  logo: 'assets/favicon.ico' #This si the logo in upper left hand corner

extra:
  search:
    language: 'en'

# You can add custom style sheets here
extra_css:
  - 'assets/stylesheets/custom-style1.css'

# List extensions here
markdown_extensions:
  - admonition #extension for the content boxes https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - pymdownx.details #extension for making content boxes expandable https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - codehilite #code block extension https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - pymdownx.superfences # same as above
  - toc:
      permalink: true # this makes the headers into links https://squidfunk.github.io/mkdocs-material/extensions/permalinks/


# TOC here. 
# The old (deprecated) heading was 'pages'. 
# Current heading is 'nav'. You cannot nest linked headings.
nav:
  - Moving to Git: index.md
  - Download Software:
    - Git: git.md
    - Git Extension: gitextension.md
    - Git LFS: lfs.md
    - Meld: meld.md
  - Set up your repository:
    - Clone the repo: clone.md
    - Set up Artifactory: artifactory.md
    - Get the remote branches: remote.md
  - Tutorials:
    - Changing files:
      - With Git Extension: working-gitExt.md
      - With Git Bash: working-gitbash.md
    - Branching:
      - What are branches: branches.md
      - With Git Extension: branching-gitExt.md
      - With Git Bash: branch-gitbash.md
    - Merging:
      - With Git Extension: merge-gitExt.md
      - With Git Bash: merge-gitbash.md
    - Cherry Pick:
      - With Git Extension: cherrypick-gitExt.md
    - Blame:
      - With Git Extension: blame-gitExt.md
    - Amend Commits:
      - Amend Commits from command line: amend.md
    - Squash Commits:
      - With Git Extension: squash-gitExt.md
      - With Git Bash: squash_all.md
    - Recover a deleted branch: recover-branch.md
    - Reverse Commits:
      - Revert Commits with Git Extension: revert-gitExt.md
      - Reset Commits with Git Extension: delete-gitExt.md
      - Recover Deleted commits: recover.md
      - Revert merge commits: revert-merge-commit.md
    - Important Concepts:
      - Fetch vs. Pull: fetch-v-pull.md
      - What is a merge conflict: conflicts.md
      - Using the mergetool: mergetool.md
      - Git log: history.md
  - Build with Jenkins:
    - Run a build in Jenkins: build.md
  - Sample workflow:
    - Complete Workflow: complete-workflow.md
  - Extras: 
    - Tips for Using Git Bash: commandline-tips.md
    - Git commands: commands.md
    - Git Extension Graph: gitExt-graph.md
    - Git Terminology: terminology.md
  - About this website: about.md
  - Github markdown: github-markdown.md